### ISSUE TITLE
Use clinical-delivery and long-term-storage tags

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/hermes#102]
This issue is meant to track the progress of the migration to using `clinical-delivery` and `long-term-storage` tags by the pipelines for delivering to Caesar and retaining the files for more than one year in Housekeeper.

Respective CG issue: https://github.com/Clinical-Genomics/cg/issues/2848

TODO:
- [x] ~`balsamic`/`balsamic-qc`/`balsamic-umi`~ Will be deprecated
- [ ] `fluffy`
- [ ] `microsalt`
- [x] ~`mip-dna`~ Will be deprecated
- [ ] `mip-rna`
- [ ] `mutant`
- [x] `rnafusion` https://github.com/Clinical-Genomics/hermes/pull/115
- [x] `taxprofiler` https://github.com/Clinical-Genomics/hermes/pull/100
- [x] `tomte` https://github.com/Clinical-Genomics/hermes/pull/105
- [x] `raredisease` https://github.com/Clinical-Genomics/hermes/pull/109

**Comment by diitaz93** [comment]
Closing as not planned. Reopen if relevant again
