### ISSUE TITLE
Centralise Hermes documentation

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/hermes#106]
It would be nice to have a space, such as a markdown file or a GitHub page, that is kept up to date and reflects all the current tags along with their descriptions, making it easy to consult.

Currently, the GitHub page [clinical-genomics.github.io/hermes/](https://clinical-genomics.github.io/hermes/) is not being deployed with the latest changes. Additionally, it lacks the descriptions for pipeline-specific tags.

**Comment by diitaz93** [comment]
Closing as not planned. Reopen when this becomes relevant again
