### ISSUE TITLE
Add MIP RNA pipeline and tags to Hermes MIP API

### ISSUE THREAD

**Issue by henrikstranneheim** [Clinical-Genomics/hermes#12]
**Bakground**
We need to transfer the files from a MIP RNA analysis run to to Housekeeper. The files tag map need to be defined in Hermes to allow the correct files to be transferred to Housekeeper when cg ask for them from the MIP RNA analysis deliverables file.

**Challenge**
It looks like Hermes currently only know of one `mip` pipeline and need to be refactored to use both `mip-dna` and `mip-rna`. The tag map needs to be defined and added to Hermes.

**Suggested soultion**
1. Refactor and extend Hermes `mip` API to allow for multiple MIP pipelines i.e. `mip-dna` and `mip-rna`
1. Add tag map of MIP RNA

**Comment by moonso** [comment]
I can work on the Hermes part and perhaps @Mropat can look at the CG integration at the same time as https://github.com/Clinical-Genomics/cg/issues/934

**Comment by henrikstranneheim** [comment]
@jemten we should also make a PR defining  the RNA tags as soon as possible
