### ISSUE TITLE
Update BALSAMIC tags & HK files definition

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/hermes#44]
**Feature**

It is necessary to restructure and redefine some of the tags used by BALSAMIC, as well as to update the .hk files according to the new version `v8.X.X`.

----

This issue can be closed when:
- [x] HK tags are reviewed and updated with respect to CG (vardict, sention (vcf, vcf-index), etc.).
- [x] The `used_by` field for each file is up to date (which files to `store`/`deliver`/`scout`, etc).
- [x] Solved inconsistent BALSAMIC tag generation (https://github.com/Clinical-Genomics/BALSAMIC/issues/848).

**Comment by ivadym** [comment]
Delivered files (AM document 2046)

- [ ] vardict.all.filtered.pass.vcf.gz / vardict.pass.vcf.gz (TGA and WES only)
- [ ] TNscope (WGS only)
- [ ] manta.pass.vcf.gz
- [ ] cnvkit.pass.vcf.gz
- [ ] tnhaplotyper.pass.vcf.gz
- [ ] tumor.merged-diagram.pdf
- [ ] tumor.merged-scatter.pdf
- [ ] tumor.merged.cnr
- [ ] merged.cram
- [ ] multiqc_report.html
- [ ] fp.fastq.gz

**Comment by ivadym** [comment]
# WGS cases

### Somatic SNV

- [ ] .tnscope.all.vcf.gz, (HK)
- [ ] .tnscope.all.vcf.gz.tbi, (HK)
- [ ] .tnscope.all.filtered.pass.vcf.gz, (HK)
- [ ] .tnscope.all.filtered.pass.vcf.gz.tbi, (HK)
- [ ] .tnhaplotyper.all.vcf.gz, (HK)
- [ ] .tnhaplotyper.all.vcf.gz.tbi, (HK)
- [ ] .tnhaplotyper.all.filtered.vcf.gz,
- [ ] .tnhaplotyper.all.filtered.vcf.gz.tbi,
- [ ] .tnhaplotyper.all.filtered.pass.vcf.gz, (HK)
- [ ] .tnhaplotyper.all.filtered.pass.vcf.gz.tbi, (HK)

### Somatic SV

- [ ] .manta.all.vcf.gz, (HK)
- [ ] .manta.all.vcf.gz.tbi, (HK)
- [ ] .manta.all.filtered.pass.vcf.gz, (HK, Scout)
- [ ] .manta.all.filtered.pass.vcf.gz.tbi, (HK, Scout)
- [ ] .delly.all.filtered.pass.vcf.gz, (HK)
- [ ] .delly.all.filtered.pass.vcf.gz.tbi, (HK)
- [ ] .delly.bcf, (HK)
- [ ] .delly.bcf.csi (HK)

### Somatic CNVs

- [ ] .ascat.all.vcf.gz, (HK)
- [ ] .ascat.all.vcf.gz.tbi, (HK)
- [ ] .ascat.all.filtered.pass.vcf.gz, (HK)
- [ ] .ascat.all.filtered.pass.vcf.gz.tbi, (HK)

### Germline SV

- [ ] .normal.manta_germline.vcf.gz, (HK)
- [ ] .normal.manta_germline.vcf.gz.tbi, (HK)
- [ ] .tumor.manta_germline.vcf.gz, (HK, Scout)
- [ ] .tumor.manta_germline.vcf.gz.tbi,  (HK, Scout)

### Germline SNV

- [ ] .normal.dnascope.vcf.gz, (HK)
- [ ] .normal.dnascope.vcf.gz.tbi, (HK)
- [ ] .tumor.dnascope.vcf.gz, (HK)
- [ ] .tumor.dnascope.vcf.gz.tbi, (HK)

### General stats

- [ ] *.all.stats
- [ ] *__summary.html

### Additional new WGS output to include

- [ ] /home/proj/stage/cancer/cases/$wgs_caseid/analysis/vcf/*.ascat.output.pdf (HK)

**Comment by ivadym** [comment]
# Panel Cases

### QC and reports

- [ ] *_report.html
- [ ] .json
- [ ] _BALSAMIC_8.2.0_graph.pdf
- [ ] multiqc_report.html
- [ ] multiqc_data.json
- [ ] fastp.json
- [ ] fastp.html

### Raw data files and Aligned files

#### tumor

- [ ] concatenated_*.fp.fastq.gz
- [ ] tumor.merged.bam
- [ ] tumor.merged.bam.bai
- [ ] tumor.merged.cram
- [ ] tumor.merged.cram.crai

#### normal
- [ ] normal.merged.bam
- [ ] normal.merged.bam.bai
- [ ] normal.merged.cram
- [ ] normal.merged.cram.crai

### Variant-caller VCF files

#### Somatic-callers SNV/INDELs
- [ ] .vardict.all.filtered.vcf.gz
- [ ] .vardict.all.filtered.vcf.gz.tbi
- [ ] .vardict.all.filtered.pass.vcf.gz
- [ ] .vardict.all.filtered.pass.vcf.gz.tbi
- [ ] .vardict.all.vcf.gz_summary.html
- [ ] .vardict.all.stats
- [ ] .TNscope_umi.all.filtered.vcf.gz
- [ ] .TNscope_umi.all.filtered.vcf.gz.tbi
- [ ] .TNscope_umi.all.filtered.pass.vcf.gz
- [ ] .TNscope_umi.all.filtered.pass.vcf.gz.tbi
- [ ] .TNscope_umi.all.vcf.gz_summary.html
- [ ] .TNscope_umi.all.stats
- [ ] .tnhaplotyper.all.filtered.vcf.gz,
- [ ] .tnhaplotyper.all.filtered.vcf.gz.tbi
- [ ] .tnhaplotyper.all.filtered.pass.vcf.gz,
- [ ] .tnhaplotyper.all.filtered.pass.vcf.gz.tbi
- [ ] .tnhaplotyper.all.vcf.gz_summary.html
- [ ] .tnhaplotyper.all.stats

#### Somatic-callers SV
- [ ] .delly.all.filtered.pass.vcf.gz
- [ ] .delly.all.filtered.pass.vcf.gz.tbi
- [ ] .delly.all.vcf.gz
- [ ] .delly.all.vcf.gz.tbi
- [ ] .delly.all.vcf.gz_summary.html
- [ ] .delly.all.stats
- [ ] .manta.all.filtered.pass.vcf.gz
- [ ] .manta.all.filtered.pass.vcf.gz.tbi
- [ ] .manta.all.vcf.gz
- [ ] .manta.all.vcf.gz.tbi
- [ ] manta.all.vcf.gz_summary.html
- [ ] .manta.all.stats

#### Somatic-callers CNV
- [ ] cnvkit.all.vcf.gz
- [ ] cnvkit.all.vcf.gz.tbi
- [ ] .cnvkit.all.filtered.pass.vcf.gz
- [ ] .cnvkit.all.filtered.pass.vcf.gz.tbi
- [ ] tumor.merged-scatter.pdf
- [ ] tumor.merged-diagram.pdf
- [ ] tumor.merged.cns
- [ ] tumor.merged.cnr
- [ ] gene_metrics
- [ ] .gene_breaks
- [ ] .cnvkit.all.vcf.gz_summary.html
- [ ] .cnvkit.all.stats

### Germline callers

#### SNV germline
- [ ] .haplotypecaller.vcf.gz
- [ ] .haplotypecaller.vcf.gz.tbi
- [ ] haplotypecaller.vcf.gz_summary.html
- [ ] .germline.tumor.haplotypecaller.all.stats
- [ ] .dnascope.vcf.gz
- [ ] .dnascope.vcf.gz.tbi
- [ ] .dnascope.vcf.gz_summary.html
- [ ] .tumor.dnascope.all.stats

#### SV germline
- [ ] .manta_germline.vcf.gz
- [ ] .manta_germline.vcf.gz.tbi
- [ ] .manta_germline.vcf.gz_summary.html
- [ ] .manta_germline.all.stats

**Comment by ivadym** [comment]
Changes:

- Added an additional HK tag (`tumor` and `normal`) to distinguish between `tumor.manta_germline.vcf.gz*` and `.normal.manta_germline.vcf.gz*` files

**Comment by ashwini06** [comment]
@keyvanelhami @moahaegglund @karlnyr : Right now, for UMI-related files, we are only storing UMI-called vcf file, but not UMI-related bam file.  It is also important to think on that part for automatic upload of UMI cases to scout. In scout IGV, if the umi-called bam file needs to be visualized, I think it's important to store that related file in HK as well. Please drop your inputs on this part as well.

**Comment by keyvanelhami** [comment]
@ashwini06 @ivadym Just so I understands everything correctly:
Are the marked different files [here](https://github.com/Clinical-Genomics/hermes/issues/44#issuecomment-996823883) the files that are going to be store in HK? Or are the marked files the files that are produced?

So I need to identify which of these files that needs to be store in HK?

**Comment by ivadym** [comment]
The marked files are the ones stored and/or delivered. Currently all the produced files, defined in `.hk`, are stored.

And it will be great if you can identify which files are stored, delivered and/or which ones should be uploaded to scout. Besides, in case of the delivered/uploaded to scout files I think it will be a good idea to designate under which tags this should be done, i.e. define the HK tags. Currently this tags are outdated and some of the defined in CG are not used at all. For this maybe it will be also useful for you to look at the HK tags that are now defined for the balsamic files: https://github.com/Clinical-Genomics/hermes/blob/5b56669e2d052f2f9a3c691451362f740974e7e2/cg_hermes/config/balsamic.py#L245
And this are the balsamic specific tags: https://github.com/Clinical-Genomics/hermes/blob/5b56669e2d052f2f9a3c691451362f740974e7e2/cg_hermes/config/balsamic.py#L7

Thanks!

**Comment by keyvanelhami** [comment]
Questions to be answered:

1) What files are delivered today.
2) Should we add additional files to deliver?
3) Go through all the stored files and identify which of those we should continue to store and not store
4) What files should be included the Scout yaml-file

**Comment by keyvanelhami** [comment]
Please look into [this ticket](https://clinical-scilifelab.supportsystem.com/scp/tickets.php?id=47321) and add which of these files that today are delivered and stored

**Comment by keyvanelhami** [comment]
I have now gone through all the WGS and panel files that are stored in HK. See the list above for mine and the our common suggestions that we have discussed during the cancer meeting. In general:

- We will stop storing intermediate vcf-files in HK `* all.filtered.vcf.gz`
- We will stop storing concat fastq-files
- We will start delivering raw vcf-file `*all.vcf.gz`  together with filtered vcf-file `*all.filtered.pass.vcf.gz`  that we today already are delivering. This applies for both SV and SNV callers
- We will start delivering germline vcf-files for both panels and WGS
- When starting to deliver `[svdb].all.filtered.pass.vcf.gz`, we will stop delivering the filtered `all.filtered.pass.vcf.gz` for the different SV variant callers (manta, delly, cnvkit).

**Questions to discuss:**
- Should we deliver both `dnascope` and `tnhaplotyer` for SNV germline (panels) and SNV somatic (WGS), or is it enough with one variant caller? If so, which variant caller?
- cnvkit.vcf.gz (PANEL) **SD** (not included in .hk during BALSAMIC workflow), @ivadym this needs to be added so we can start delivering it. Same with `cnvkit.vcf.gz.tbi`. @khurrammaqbool these are the "raw vcf", right?

**Comment by karlnyr** [comment]
Incredible work! Should we perhaps deliver both until we will produce fusion vcfs?

**Comment by ivadym** [comment]
Thank you for going through this @keyvanelhami! 🎆 

And yes, the *.vcf.gz.tbi files are the raw vcfs that still has to be added to HK.

**Comment by vwirta** [comment]
Thanks @keyvanelhami 

Just one thing... I'm not sure I understand the question below? Could you please clarify?
> * Should we deliver both `dnascope` and `tnhaplotyer` for SNV germline (panels) and SNV somatic (WGS), or is it enough with one variant caller? If so, which variant caller?

**Comment by moahaegglund** [comment]
I think we should add a new delivery tag for the UMI files and separate that from the regular BALSAMIC delivery (for example `cg deliver analysis -d balsamic-umi`). We are talking about making BALSAMIC and BALSAMIC-UMI to two separate workflows, I think it would be good to separate the delivery now already.

**Comment by keyvanelhami** [comment]
> Thanks @keyvanelhami
> 
> Just one thing... I'm not sure I understand the question below? Could you please clarify?
> 
> > * Should we deliver both `dnascope` and `tnhaplotyer` for SNV germline (panels) and SNV somatic (WGS), or is it enough with one variant caller? If so, which variant caller?

- For panels and T/N-analysis, we are today producing two vcf-files for the germline variants through `dnascope` and `tnhaplotyer`. 
- For WGS we are producing two vcf-files for somatic variants through `dnascope` and `tnhaplotyer`. 

So I am basically wondering if we should deliver the vcf for both callers or only use one?

**Comment by keyvanelhami** [comment]
> I think we should add a new delivery tag for the UMI files and separate that from the regular BALSAMIC delivery (for example `cg deliver analysis -d balsamic-umi`). We are talking about making BALSAMIC and BALSAMIC-UMI to two separate workflows, I think it would be good to separate the delivery now already.

I have added a **UMI** tag in the list of stored samples for Panels for the files created for UMI. These files can be included in `balsamic-umi` flag.
@ashwini06 Do we already know now what files that will be created for the new balsamic-umi workflow? If so, we can specify the remaining files that should be stored/delivered for that workflow

**Comment by ashwini06** [comment]
> * For panels and T/N-analysis, we are today producing two vcf-files for the germline variants through `dnascope` and `tnhaplotyer`.
> * For WGS we are producing two vcf-files for somatic variants through `dnascope` and `tnhaplotyer`.
> 
> So I am basically wondering if we should deliver the vcf for both callers or only use one?

@keyvanelhami : Just to clarify, for panels we have 2 germline SNV callers (`sentieons DNAscope` and `gatk haplotypecaller`) and for WGS we have only one germline SNV caller (I,e `sentieons DNAscope`)

For SV germline calling (panels and WGS), we have only results from `manta` caller

**TNhaplotyper* is the second caller for reporting SNV somatic variants in both panel and WGS cases

So if the question is about the choice of selecting one caller for SNV germline (DNAscope vs haplotypecaller), there are few research articles performing benchmarking with inclusion of these callers. One of the paper is [this](https://academic.oup.com/bib/article/22/3/bbaa148/5875142?login=true), according to this study both callers had similar accuracy in reporting SNPs and INDELS for germline calling ([Figure 2](https://academic.oup.com/view-large/figure/248018397/bbaa148f2.tif)), but in terms of usage of computational resources, sentieon DNAscope performed better ([Figure 6](https://academic.oup.com/view-large/figure/248018416/bbaa148f6.tif))

**Comment by vwirta** [comment]
> > * For panels and T/N-analysis, we are today producing two vcf-files for the germline variants through `dnascope` and `tnhaplotyer`.
> > * For WGS we are producing two vcf-files for somatic variants through `dnascope` and `tnhaplotyer`.
> > 
> > So I am basically wondering if we should deliver the vcf for both callers or only use one?
> 
> @keyvanelhami : Just to clarify, for panels we have 2 germline SNV callers (`sentieons DNAscope` and `gatk haplotypecaller`) and for WGS we have only one germline SNV caller (I,e `sentieons DNAscope`)
> 
> For SV germline calling (panels and WGS), we have only results from `manta` caller
> 
> *_TNhaplotyper_ is the second caller for reporting SNV somatic variants in both panel and WGS cases
> 
> So if the question is about the choice of selecting one caller for SNV germline (DNAscope vs haplotypecaller), there are few research articles performing benchmarking with inclusion of these callers. One of the paper is [this](https://academic.oup.com/bib/article/22/3/bbaa148/5875142?login=true), according to this study both callers had similar accuracy in reporting SNPs and INDELS for germline calling ([Figure 2](https://academic.oup.com/view-large/figure/248018397/bbaa148f2.tif)), but in terms of usage of computational resources, sentieon DNAscope performed better ([Figure 6](https://academic.oup.com/view-large/figure/248018416/bbaa148f6.tif))

thanks @keyvanelhami and @ashwini06 for me it sounds it would be easiest to store the DNAscope files for both panel and WGS data.

**Comment by keyvanelhami** [comment]
**Actions** remaining before this issue is can be closed:

- @ashwini06 Please check the suggestions for UMI.
- @moahaegglund Please go through all files and comment if something should be changed or is missing

**Comment by ivadym** [comment]
Thank you all for your contributions 🎈

FINALLY closing via https://github.com/Clinical-Genomics/hermes/pull/56

**Comment by henrikstranneheim** [comment]
@ivadym well done! 🎉
