### ISSUE TITLE
Update Hermes dependencies

### ISSUE THREAD

**Issue by raysloks** [Clinical-Genomics/hermes#72]
Updating Hermes dependencies to more recent versions

Also some security updates a la https://github.com/Clinical-Genomics/hermes/security/dependabot

**Comment by raysloks** [comment]
Initially, I just used the latest version of poetry (1.4.0) and ran `poetry update`. However, the CI tests failed because they use version 1.2.0. I tried running `poetry update` with version 1.2.0 and 1.2.1, but it gets stuck on "resolving dependencies" forever.
Would swapping to 1.4.0 for the tests be the play here?

**Comment by henrikstranneheim** [comment]
Yes, they should be  in sync
