### ISSUE TITLE
Different MIP files share same tags

### ISSUE THREAD

**Issue by ivadym** [Clinical-Genomics/hermes#73]
Mainly MIP VCFs and their indexes are being saved in Housekeeper with the same tags:

<img width="1644" alt="Screenshot 2023-04-03 at 15 44 21" src="https://user-images.githubusercontent.com/26309194/229528130-f1dbec57-0703-47c2-b38e-e2c32e9a3da1.png">

We have in Hermes specific tags for index files that are currently not used for MIP:
https://github.com/Clinical-Genomics/hermes/blob/e746eb6abcd16522fecc475f6c84dd7d01eabc5b/cg_hermes/config/tags.py#L41

This became a problem after extracting the latest files from Housekeeper for Scout uploads (https://github.com/Clinical-Genomics/cg/pull/1868), necessary to address filtered VCFs in Balsamic. The solution has been reverted in CG for MIP (https://github.com/Clinical-Genomics/cg/pull/1895), but this is still an issue for future development.

### Suggested solution
 - Use the `index_tags` field to give the index file a unique tag
https://github.com/Clinical-Genomics/hermes/blob/e746eb6abcd16522fecc475f6c84dd7d01eabc5b/cg_hermes/config/mip_dna.py#L41
- Make sure that it doesn't break anything upstream (CG, uploads to genotype, loqusdb, etc.)

**Comment by henrikstranneheim** [comment]
@jemten Could you look into making a patch in MIP for this?

**Comment by jemten** [comment]
I don't think we need to patch MIP as the indexes are already saved to the deliverables file. We need to update hermes though. And also check that CG/Scout doesn't rely too much on this unintended feature, retrieving both the file and its index. We also need to check if we need to keep backwards compatibility as vcf:s and alignment file with indexes generated by MIP to this data are stored in HK under the same key. I can look into it though

**Comment by ivadym** [comment]
GENS files are also affected: https://github.com/Clinical-Genomics/cg/issues/2630.

**Comment by henrikstranneheim** [comment]
Added to refinement 9/11

**Comment by Vince-janv** [comment]
## Decision:
- Update Hermes to add index-tag to index files @peterpru @ivadym 
- Remove work-arounds in cg (genotype upload, delivery-report) @ivadym @Vince-janv 
- Retroactively add the index-tag to all index files in housekeeper @jemten @Clinical-Genomics/sysdev

**Comment by ivadym** [comment]
MIP is planned to be deprecated, so the effort isn't worth it. Closing!
